
mtscad = {}

local MP = minetest.get_modpath("mtscad")
dofile(MP .. "/context/new.lua")
dofile(MP .. "/context/basics.lua")
dofile(MP .. "/context/execute.lua")
dofile(MP .. "/context/translate.lua")
dofile(MP .. "/context/rotate.lua")
dofile(MP .. "/context/line.lua")
dofile(MP .. "/context/polygon.lua")
dofile(MP .. "/context/cube.lua")
dofile(MP .. "/context/sphere.lua")
dofile(MP .. "/context/dome.lua")
dofile(MP .. "/context/slope.lua")
dofile(MP .. "/context/cylinder.lua")
dofile(MP .. "/context/pattern.lua")
dofile(MP .. "/origin.lua")
dofile(MP .. "/rotate_facedir.lua")
dofile(MP .. "/transform.lua")
dofile(MP .. "/util/merge.lua")
dofile(MP .. "/util/job_context.lua")
dofile(MP .. "/chat/load.lua")
dofile(MP .. "/chat/origin.lua")
