
mtscad = {}

local MP = minetest.get_modpath("mtscad")
dofile(MP .. "/context/new.lua")
dofile(MP .. "/context/with.lua")
dofile(MP .. "/context/set_node.lua")
dofile(MP .. "/context/execute.lua")
dofile(MP .. "/context/translate.lua")
dofile(MP .. "/context/rotate.lua")
dofile(MP .. "/context/line.lua")
dofile(MP .. "/context/polygon.lua")
dofile(MP .. "/context/cube.lua")
dofile(MP .. "/context/sphere.lua")
dofile(MP .. "/context/dome.lua")
dofile(MP .. "/context/slope.lua")
dofile(MP .. "/context/scale.lua")
dofile(MP .. "/context/param2.lua")
dofile(MP .. "/context/cylinder.lua")
dofile(MP .. "/context/pattern.lua")
dofile(MP .. "/context/mirror.lua")
dofile(MP .. "/util/extents.lua")
dofile(MP .. "/util/matrix.lua")
dofile(MP .. "/util/origin.lua")
dofile(MP .. "/util/rotate_facedir.lua")
dofile(MP .. "/util/transform.lua")
dofile(MP .. "/util/merge.lua")
dofile(MP .. "/util/load_module.lua")
dofile(MP .. "/util/job_context.lua")
dofile(MP .. "/chat/load.lua")
dofile(MP .. "/chat/origin.lua")
